from __future__ import annotations

import json
from pathlib import Path

from pilot.plugins.manager import PluginManager
from pilot.plugins.security import PluginValidationError, confine_to_root, validate_plugin_name
from pilot.utils import installed_plugins_dir, make_private_directory


def scaffold_plugin(slug: str, label: str | None = None) -> Path:
    """Generate a working backend+frontend skeleton for a new installed plugin.

    Raises `PluginValidationError` if `slug` is invalid, reserved by a
    bundled plugin, or a directory already exists for it.
    """
    validate_plugin_name(slug)
    if PluginManager.is_bundled(slug):
        raise PluginValidationError(f"'{slug}' is a bundled plugin name and cannot be reused.")

    plugins_root = installed_plugins_dir()
    make_private_directory(plugins_root, parents=True)
    plugin_dir = confine_to_root(plugins_root, slug)
    if plugin_dir.exists():
        raise PluginValidationError(f"A plugin directory already exists for '{slug}'.")

    label = label.strip() if label and label.strip() else slug.replace("-", " ").replace("_", " ").title()
    identifier = slug.replace("-", "_")

    (plugin_dir / "frontend" / "src").mkdir(parents=True)
    (plugin_dir / "__init__.py").write_text("")
    (plugin_dir / "plugin.py").write_text(_plugin_py(slug, identifier))
    (plugin_dir / "api.py").write_text(_api_py(slug, identifier))
    (plugin_dir / "README.md").write_text(_readme_md(slug, label))
    (plugin_dir / "frontend" / "package.json").write_text(_package_json(slug))
    (plugin_dir / "frontend" / "vite.config.js").write_text(_vite_config_js())
    (plugin_dir / "frontend" / "src" / "index.js").write_text(_index_js(slug, label))
    (plugin_dir / "frontend" / "src" / "Settings.vue").write_text(_settings_vue(slug, label))

    return plugin_dir


def _plugin_py(slug: str, identifier: str) -> str:
    return f'''from __future__ import annotations

from pilot.plugins.base import BasePilotPlugin


class Plugin(BasePilotPlugin):
    @property
    def name(self) -> str:
        return {json.dumps(slug)}

    def register_routes(self, app) -> None:
        from .api import {identifier}_bp

        api_prefix = app.config.get("API_V1_PREFIX", "/api/v1")
        app.register_blueprint({identifier}_bp, url_prefix=f"{{api_prefix}}/{slug}")
'''


def _api_py(slug: str, identifier: str) -> str:
    return f'''from __future__ import annotations

from flask import Blueprint, jsonify

{identifier}_bp = Blueprint({json.dumps(slug)}, __name__)


@{identifier}_bp.get("")
def status():
    """GET /api/v1/{slug} - replace with your plugin's own routes."""
    return jsonify({{"message": "Hello from the {slug} plugin!"}})
'''


def _readme_md(slug: str, label: str) -> str:
    return f'''# {label}

Generated by Pilot's plugin scaffold. See `docs/plugin-frontend.md` in the
Pilot repo for the full contract this follows.

## Backend

- `plugin.py` - the `Plugin` class Pilot discovers and loads. Required.
- `api.py` - a Flask blueprint mounted at `/api/v1/{slug}`. Add routes here.

Routes are registered once when the Admin process starts, so restart it
after adding or editing a route - no rebuild needed, but a restart is:
`bench -b <name> stop` then `start` (or, in production mode,
`bench -b <name> restart --admin`).

## Frontend (optional - delete `frontend/` if you don't need a Settings UI)

```
cd frontend
npm install
npm run build
```

Then reload the Admin UI in your browser - "{label}" will appear under
Settings. Rebuild after every frontend change; there's no dev-server/HMR
path for plugins (see docs/plugin-frontend.md for why).

`vue`, `vue-router`, and `frappe-ui` are external - use them like any other
component in Pilot's own frontend, don't add your own copy. Style with
frappe-ui components and Tailwind classes Pilot's own build already
generates - don't add a Tailwind/PostCSS build of your own; a second,
independently-built utility CSS file will override core's responsive
styles sitewide (documented in `docs/plugin-frontend.md`).
'''


def _package_json(slug: str) -> str:
    return json.dumps(
        {
            "name": f"pilot-plugin-{slug}-frontend",
            "version": "1.0.0",
            "private": True,
            "type": "module",
            "scripts": {"build": "vite build"},
            "devDependencies": {
                "@vitejs/plugin-vue": "^6.0.8",
                "frappe-ui": "1.0.0-beta.16",
                "vite": "^8.1.5",
                "vue": "^3.5.0",
                "vue-router": "^4.4.0",
            },
        },
        indent=2,
    ) + "\n"


def _vite_config_js() -> str:
    return """import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import path from 'path'
import frappeuiPlugin from 'frappe-ui/vite'

// vue/vue-router/frappe-ui stay external, resolved at runtime through the
// Admin UI's import map, so this plugin shares the exact same instances
// core uses instead of bundling its own copies. See docs/plugin-frontend.md
// in the Pilot repo.
export default defineConfig({
  plugins: [
    frappeuiPlugin({
      lucideIcons: true,
      frappeProxy: false,
      jinjaBootData: false,
      buildConfig: false,
    }),
    vue(),
  ],
  define: {
    'process.env.NODE_ENV': JSON.stringify('production'),
  },
  build: {
    outDir: 'dist',
    lib: {
      entry: path.resolve(__dirname, 'src/index.js'),
      formats: ['es'],
      fileName: () => 'index.js',
    },
    rollupOptions: {
      external: ['vue', 'vue-router', 'frappe-ui'],
      output: {
        inlineDynamicImports: true,
      },
    },
  },
})
"""


def _index_js(slug: str, label: str) -> str:
    return f"""import Settings from './Settings.vue'

export function init(registry) {{
  registry.registerSettingsSection({{
    id: {json.dumps(slug)},
    label: {json.dumps(label)},
    icon: 'lucide-puzzle',
    component: Settings,
  }})
}}
"""


def _settings_vue(slug: str, label: str) -> str:
    return f"""<template>
  <div class="flex flex-col gap-4">
    <p class="text-ink-gray-6 text-p-base">
      This is the starting point for the {label} plugin's Settings page.
      Edit <code>frontend/src/Settings.vue</code>, then run
      <code>npm run build</code> inside <code>frontend/</code> and reload.
    </p>
    <div class="flex items-center gap-2">
      <Button variant="solid" :loading="loading" @click="ping">Ping the backend</Button>
      <span v-if="message" class="text-ink-gray-7 text-p-base">{{{{ message }}}}</span>
      <span v-if="error" class="text-ink-red-5 text-p-base">{{{{ error }}}}</span>
    </div>
  </div>
</template>

<script setup>
import {{ ref }} from 'vue'
import {{ Button }} from 'frappe-ui'

const loading = ref(false)
const message = ref('')
const error = ref('')

async function ping() {{
  loading.value = true
  message.value = ''
  error.value = ''
  try {{
    const res = await fetch('/api/v1/{slug}', {{ credentials: 'same-origin' }})
    const data = await res.json()
    message.value = data.message || JSON.stringify(data)
  }} catch (e) {{
    error.value = e.message
  }} finally {{
    loading.value = false
  }}
}}
</script>
"""
